import * as THREE from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import { mergeGeometries } from "three/examples/jsm/utils/BufferGeometryUtils.js";
import { ConvexGeometry } from "three/examples/jsm/geometries/ConvexGeometry.js";
import { computeBoundsTree, disposeBoundsTree, acceleratedRaycast } from "three-mesh-bvh";
import { PhysicsWorld, CollisionGroups } from "../physics/PhysicsWorld";
import { GivreConfig as givre } from "./GivreConfig";
import { getQualitySettings } from "../game/GraphicsQuality";
import mapModelUrl from "../assets/MAP/Givre/givre_01.glb?url";
import backdropModelUrl from "../assets/MAP/Givre/givre_01_fond.glb?url";
import mapPhysicsData from "../assets/MAP/Givre/givre_01.physics.json";

/**
 * "GIVRE 01 — Station alpine" (8 players, 280 × 220 m).
 *
 * Visuals: givre_01.glb (74 objects / ~38k tris / 15
 * untextured PBR materials, metres, already Y-up — NO extra rotation or
 * scale) MERGED BY MATERIAL at load time → ~15 draw calls. The
 * out-of-bounds plain + mountains (givre_01_fond.glb, no shadow, no
 * collision) live in a separate `backdrop` group that never joins the
 * beam raycast hittables.
 *
 * Collisions: the Yard-format physics JSON generated by
 * scripts/generate-givre-colliders.mjs — 117 fixed cuboids + 13 convex
 * hulls (absolute world vertices: 3 ramps at ~12°, rails, central block,
 * boiler pipes) + 2 PLAYER CLIPS over the low roofs in
 * front of the gallery (CollisionGroups.PLAYER_CLIP: they stop character
 * controllers only — shots and lines of sight pass through). Never a
 * trimesh.
 *
 * Lighting: the map's own rig from GivreConfig (sun + hemisphere; sRGB
 * output without tone mapping is applied by Game).
 */

// BVH-accelerated raycasting (idempotent — same prototypes as Jungle/Yard).
THREE.BufferGeometry.prototype.computeBoundsTree = computeBoundsTree;
THREE.BufferGeometry.prototype.disposeBoundsTree = disposeBoundsTree;
THREE.Mesh.prototype.raycast = acceleratedRaycast;

interface GivreColliderEntry {
  id: string;
  type: "cuboid" | "convexHull";
  position?: number[];
  halfExtents?: number[];
  rotation?: number[];
  vertices?: number[][];
  purpose?: string;
}

/** Named XZ rectangle (callouts / stats) straight from the export. */
export interface GivreZone {
  id: string;
  name: string;
  kind: string;
  floorY: number;
  min: number[];
  max: number[];
}

export class GivreMap {
  /** Playable visual (merged meshes) + lights — joins the beam hittables. */
  readonly group = new THREE.Group();
  /** Out-of-bounds plain + mountains — added to the scene by Game, never hittable. */
  readonly backdrop: THREE.Group;
  /** Collider (magenta) / playerClip (cyan) wireframes — hidden by default. */
  readonly colliderDebug: THREE.Group;
  /** Named zones (callouts). */
  readonly zones: GivreZone[];

  private constructor(physics: PhysicsWorld, mapScene: THREE.Group, backdrop: THREE.Group) {
    const data = mapPhysicsData as unknown as {
      colliders: GivreColliderEntry[];
      playerClips: GivreColliderEntry[];
      zones: GivreZone[];
    };
    this.zones = data.zones;

    this.group.name = "givre_01";
    this.group.add(mergeByMaterial(mapScene));
    this.buildLighting();

    backdrop.name = "givre_01_fond";
    backdrop.traverse((o) => {
      const mesh = o as THREE.Mesh;
      if (!mesh.isMesh) return;
      mesh.castShadow = false;
      mesh.receiveShadow = false;
      mesh.raycast = () => {}; // purely visual
    });
    this.backdrop = backdrop;

    // ---- Fixed colliders (created ONCE; hull vertices already absolute) ----
    for (const c of data.colliders) {
      if (!addCollider(physics, c)) console.warn(`GivreMap: collider failed for "${c.id}"`);
    }
    // ---- Player clips: character controllers only (never shots / LOS) ----
    for (const c of data.playerClips) {
      if (!addCollider(physics, c, CollisionGroups.PLAYER_CLIP)) {
        console.warn(`GivreMap: player clip failed for "${c.id}"`);
      }
    }

    this.colliderDebug = createColliderDebug(data.colliders, data.playerClips);
  }

  /** Loads both GLBs and builds every fixed collider. */
  static async create(physics: PhysicsWorld): Promise<GivreMap> {
    const loader = new GLTFLoader();
    let map;
    let backdrop;
    try {
      [map, backdrop] = await Promise.all([
        loader.loadAsync(mapModelUrl),
        loader.loadAsync(backdropModelUrl),
      ]);
    } catch (err) {
      throw new Error(`GivreMap: failed to load givre_01.glb / givre_01_fond.glb — ${String(err)}`);
    }
    return new GivreMap(physics, map.scene, backdrop.scene);
  }

  /** Zone name under a position (the gallery at Y = 6 wins over the ground). */
  zoneAt(x: number, y: number, z: number): string | null {
    let best: GivreZone | null = null;
    for (const zn of this.zones) {
      if (x < zn.min[0] || x > zn.max[0] || z < zn.min[1] || z > zn.max[1]) continue;
      if (!best || Math.abs(y - zn.floorY) < Math.abs(y - best.floorY)) best = zn;
    }
    return best ? best.name : null;
  }

  /**
   * Alpine midday rig (see GivreConfig):
   *  - HemisphereLight: cool sky over light snow bounce (π × Blender strength).
   *  - DirectionalLight sun (ENE, 36°): the only shadow caster; its frustum
   *    covers the whole 280 m playfield.
   */
  private buildLighting(): void {
    const hemi = new THREE.HemisphereLight(
      givre.ambientSkyColor,
      givre.ambientGroundColor,
      givre.ambientIntensity,
    );
    this.group.add(hemi);

    const sun = new THREE.DirectionalLight(givre.sunLightColor, givre.sunLightIntensity);
    sun.position
      .set(givre.sunDirection.x, givre.sunDirection.y, givre.sunDirection.z)
      .normalize()
      .multiplyScalar(givre.sunDistance);
    sun.castShadow = true;
    const shadowRes = getQualitySettings().shadowMapSize;
    sun.shadow.mapSize.set(shadowRes, shadowRes);
    const cam = sun.shadow.camera;
    cam.left = -givre.shadowExtent;
    cam.right = givre.shadowExtent;
    cam.top = givre.shadowExtent;
    cam.bottom = -givre.shadowExtent;
    cam.near = 1;
    cam.far = givre.sunDistance * 2 + 100;
    cam.updateProjectionMatrix();
    sun.shadow.bias = -0.0005;
    sun.shadow.normalBias = 0.05;
    // The target stays at the origin (default) — the map is centred.
    this.group.add(sun);
  }
}

/**
 * Merges every static mesh of the GLB by material (one glTF primitive = one
 * three.js Mesh with one material, shared between primitives): 225
 * primitives → ~15 draw calls. Geometry is baked into world space; only
 * position + normal survive (the materials are untextured).
 */
function mergeByMaterial(root: THREE.Object3D): THREE.Group {
  root.updateMatrixWorld(true);
  const byMaterial = new Map<THREE.Material, THREE.BufferGeometry[]>();
  root.traverse((o) => {
    const mesh = o as THREE.Mesh;
    if (!mesh.isMesh) return;
    const material = mesh.material as THREE.Material;
    const geom = mesh.geometry.clone().applyMatrix4(mesh.matrixWorld);
    for (const name of Object.keys(geom.attributes)) {
      if (name !== "position" && name !== "normal") geom.deleteAttribute(name);
    }
    const list = byMaterial.get(material) ?? [];
    list.push(geom);
    byMaterial.set(material, list);
  });

  const out = new THREE.Group();
  out.name = "givre_01_merged";
  for (const [material, geoms] of byMaterial) {
    const merged = mergeGeometries(geoms, false);
    geoms.forEach((g) => g.dispose());
    if (!merged) throw new Error(`GivreMap: merge failed for material ${material.name}`);
    merged.computeBoundingBox();
    merged.computeBoundingSphere();
    // BVH per merged mesh: O(log n) beam/hitscan raycasts (built once).
    merged.computeBoundsTree();
    const mesh = new THREE.Mesh(merged, material);
    mesh.name = `givre_${material.name}`;
    // The emissive ceiling lamps don't need to cast; everything else does.
    mesh.castShadow = material.name !== "GIV_Lampe";
    mesh.receiveShadow = true;
    mesh.matrixAutoUpdate = false;
    mesh.updateMatrix();
    out.add(mesh);
  }
  return out;
}

/** One fixed collider of the Yard-format JSON. Returns false on failure. */
function addCollider(
  physics: PhysicsWorld,
  c: GivreColliderEntry,
  collisionGroups?: number,
): boolean {
  if (c.type === "cuboid" && c.position && c.halfExtents) {
    // Axis-aligned by construction (identity rotation in the export).
    physics.addStaticBox(
      c.position[0],
      c.position[1],
      c.position[2],
      c.halfExtents[0] * 2,
      c.halfExtents[1] * 2,
      c.halfExtents[2] * 2,
      undefined,
      collisionGroups !== undefined ? { collisionGroups } : undefined,
    );
    return true;
  }
  if (c.type === "convexHull" && c.vertices) {
    const flat = new Float32Array(c.vertices.flat());
    const collider = physics.addStaticConvexHull(flat);
    if (collider && collisionGroups !== undefined) collider.setCollisionGroups(collisionGroups);
    return collider !== null;
  }
  return false;
}

/** Wireframes: colliders magenta, player clips cyan. Hidden by default. */
function createColliderDebug(
  colliders: GivreColliderEntry[],
  clips: GivreColliderEntry[],
): THREE.Group {
  const group = new THREE.Group();
  group.name = "givre_colliders_debug";
  group.visible = false;
  group.userData.noOutline = true; // never outlined (GivreOutlinePass)
  const solidMat = new THREE.MeshBasicMaterial({ color: 0xff2fd0, wireframe: true, toneMapped: false });
  const clipMat = new THREE.MeshBasicMaterial({ color: 0x2fd0ff, wireframe: true, toneMapped: false });
  const add = (c: GivreColliderEntry, mat: THREE.Material) => {
    let geom: THREE.BufferGeometry;
    if (c.type === "cuboid" && c.position && c.halfExtents) {
      geom = new THREE.BoxGeometry(c.halfExtents[0] * 2, c.halfExtents[1] * 2, c.halfExtents[2] * 2);
      geom.translate(c.position[0], c.position[1], c.position[2]);
    } else if (c.type === "convexHull" && c.vertices) {
      geom = new ConvexGeometry(c.vertices.map((p) => new THREE.Vector3(p[0], p[1], p[2])));
    } else {
      return;
    }
    const mesh = new THREE.Mesh(geom, mat);
    mesh.name = c.id;
    mesh.raycast = () => {}; // debug only: never a hit target
    mesh.frustumCulled = false;
    group.add(mesh);
  };
  colliders.forEach((c) => add(c, solidMat));
  clips.forEach((c) => add(c, clipMat));
  return group;
}
